# fly.toml app configuration file generated for urheiluseura on 2023-05-22T15:50:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "urheiluseura"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
